FROM node:22.14

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

# Для prod - используем prod API
ENV VITE_API_URL=https://backend.tma.thelifemission.com
ENV VITE_APP_ENV=production
ENV VITE_DEBUG=false

RUN npm run build

CMD ["npm", "run", "start:prod"]
