FROM node:22.14

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

# Для dev - используем dev API
ENV VITE_API_URL=https://backend-dev.tma.thelifemission.com
ENV VITE_APP_ENV=development
ENV VITE_DEBUG=true

RUN npm run build:dev

CMD ["npm", "run", "start:prod"]
